name: Build With Gradle

on:
  pull_request:
  workflow_call:
    outputs:
      version:
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest LunaChat.jar
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/ucchyocean/LunaChat/releases/latest)
          ASSET_URL=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | select(.name == "LunaChat.jar") | .browser_download_url')
          curl -L -o libs/LunaChat.jar "$ASSET_URL"

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Get version from build.gradle
        id: get_version
        run: |
          VERSION=$(./gradlew -q printVersion)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DiscordConnect
          path: build/libs
