name: Create Draft Release

on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  build:
    uses: ./.github/workflows/build.yml

  create-draft-release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: DiscordConnect

      - name: Get version from build.gradle
        run: |
          echo $(./gradlew -q printVersion) >> $GITHUB_ENV

      - name: Create GitHub Draft Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.pull_request.title }}
          tag_name: ${{ env.VERSION }}
          body: ${{ github.event.pull_request.body }}
          files: "*.jar"
          draft: true
          fail_on_unmatched_files: true
